---
title: "R Startup and Library Paths"
output: html_document
---

## Renviron files

Step 1: Was --no-environ set on the command line? - If so, do not search for site and user files to process environmental variables.
Step 2: Check the environment variable R_ENVIRON for the path to the site environment file.
    + I assume R_ENVIRON has to be an OS-level environment variable because I'm not sure where else you could set it.
    + I suppose you could set it in the R_HOME/etc/Renviron file, but everywhere I've read says you should not edit that file.
Step 3: If R_ENVIRON is unset (which by default it is), go to R_HOME/etc/Renviron.site (if it exists, sometimes it does and sometimes it does not. not terribly important.) and set environmental variables for your R session.
Step 4: Next check the R_ENVIRON_USER environment variable for the path to the user environment file.
    + This can be set either in in the site-level environment file (although it wouldn't make much sense to set the same user file for all users) OR it can be set using an OS level environment variable (probably the better way to do it).
Step 5: if the R_ENVIRON_USER environment variable is unset (which by default it is), then check R's current working directory for a ".Renviron" file. Generally this is where an R project's .Renviron file will be pulled in.
Step 6: If R's current working directory does not have a .Renviron file, look in the user's home directory ~/.Renviron.

## Rprofile files

Step 1: Was --no-site-file set at the command line? If so, do not search for the site-wide startup profile.
Step 2: If it was not set, check the R_PROFILE environment variable for the location of the site-wide Rprofile.
    + You can set this value at the OS level, or in one of your .Renviron or Renviron.site files. I suppose the benefits of setting this variable at the OS level is it will be easier for non-R processes to access this variable. However, I don't know when such a siutation would occur so it seems like it would be good to set this an .Renviron or Renviron.site file to keep all your R stuff together. However, either way is fine, and it'll work the same no matter how it's set-up.
Step 3: If R_PROFILE is unset (which it is by default) check the Rprofile.site file stored in R_HOME/etc/. This will usually exist.
Step 4: Was --no-init-file set at the command line? If so, do not look for a user profile.
Step 5: If it was not set, check the value of the environment variable R_PROFILE_USER for the path to the user's profile.
    + Like above, you can set this at the OS lvel, or in one of your .Renviron or Renviron.site files. It's your choice.
Step 6: If R_PROFILE_USER is undefined (by default it is), check R's current working directory for .Rprofile. Generally speaking this is where a project's .Rprofile will be stored.
Step 7: If no .Rprofile is found in R's current working directory, check the user's home directory: ~/.Rprofile.

Some misc.

1. A site-wide file and EITHER an R project or user file can be loaded at the same time.
2. The environment files are plain-text files in the form of `name=vale`. They are not R code. You can comment out things with `#`.
3. On Unix/Linux versions of R, there is a file `R_HOME/etc/Renviron` which is read very early in the start-up processing. It contains environment variables set by R in the configure process. Values in that file can be overriden in site or user environment files. The Renviron file SHOULD NOT be changed itself.
4. Site-wide files are read by all users. User-wide files are read only by the user.
5. Unlike environment files, profiles are R scripts and run R code. However, it's widely discouraged from putting R code in your profile which would limit the reproduciblity of your code.

## Links

* https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html
* https://csgillespie.github.io/efficientR/3-3-r-startup.html#r-startup
* https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/
* https://rstats.wtf/r-startup.html (has very interesting photo)
* https://csgillespie.github.io/efficientR/set-up.html#r-startup
* https://devconnected.com/how-to-set-and-unset-environment-variables-on-linux/
* https://stat.ethz.ch/R-manual/R-devel/library/base/html/EnvVar.html